### ISSUE TITLE
Use `exportSourcemap` instead of `generateSourceMap`

### ISSUE THREAD

**Issue by smizell** [apiaryio/fury-adapter-swagger#26]
See https://github.com/apiaryio/plutonium/pull/61/files#r47074724

**Comment by danielgtaylor** [comment]
Relevant conversation:

https://github.com/apiaryio/fury-adapter-apib-parser/pull/1#discussion_r39368909

Up to date stats:

Query | Count
-------- | -------:
[`exportSourcemap`](https://github.com/search?q=exportSourcemap&type=Code&utf8=%E2%9C%93) | 106
[`exportSourcemaps`](https://github.com/search?utf8=%E2%9C%93&q=exportSourcemaps&type=Code&ref=searchresults) | 10
[`generateSourceMap`](https://github.com/search?utf8=%E2%9C%93&q=generateSourceMap&type=Code&ref=searchresults) | 1011
[`generateSourceMaps`](https://github.com/search?utf8=%E2%9C%93&q=generateSourceMaps&type=Code&ref=searchresults) | 7751

From a grammar standpoint I have no idea if it should be singular or plural. Since we are parsing a single input it feels like we should generate a single source map, but I could be wrong about that.

**Comment by pksunkara** [comment]
Okay, I think, it's better if we use `generateSourceMap` in protagonist and make it backward compatible. What do you think @smizell ?

**Comment by smizell** [comment]
I think either singular or plural is good, though technically it is multiple source maps (each element having its own source map).

**Comment by pksunkara** [comment]
Okay, let's go with `generateSourceMap`.

**Comment by smizell** [comment]
:+1:

**Comment by pksunkara** [comment]
Closing this now since no change is needed.
